spring:
  application:
    name: user-service

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,loggers
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

logging:
  pattern:
    level: "%5p [traceId=%X{traceId:-}, spanId=%X{spanId:-}]"
  level:
    root: INFO
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG   # si quer�s ver queries SQL

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}

pool:
  auth:
    url: ${AUTH_SERVICE_URL:http://localhost:8081}
