spring:
  application:
    name: user-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:9036/user_service}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root_psw}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
    defer-datasource-initialization: true

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,loggers
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0
    baggage:
      remote-fields:
        - X-Request-Id
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_SERVER:http://localhost:9001/api/v2/spans}

logging:
  level:
    root: INFO
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG   # si quer�s ver queries SQL

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:9061/eureka/}

pool:
  auth:
    url: ${AUTH_SERVICE_URL:http://localhost:9080/auth}
